name: texas_covid
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=2.1.0
  - matplotlib=3.2.1
  - numpy=1.18.1
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.7.6
  - scipy=1.4.1
  - xlrd=1.2.0
