name: texas_covid
channels:
  - conda-forge
  - defaults
dependencies:
  - dash=1.11.0
  - ipywidgets=7.5.1
  - jupyterlab=2.1.0
  - matplotlib=3.2.1
  - numpy=1.18.1
  - pandas=1.0.3
  - pip=20.0.2
  - plotly=4.6.0
  - pymc3=3.8
  - python=3.7.6
  - scipy=1.4.1
  - xlrd=1.2.0
